import type {u64, i128} from "@stellar/stellar-sdk/contract";

export interface Order {
    id: u64;
    kind: OrderKind;
    selling: string;
    buying: string;
    amount: i128;
    quote: i128;
    owner: string;
    price: i128;
    expires: u64;
}

export interface Trade {
    bought: i128;
    id: u64;
    maker: string;
    order: u64;
    sold: i128;
    taker: string;
}

export enum OrderKind {
    Limit = 1,
    Fill = 2,
    FillOrKill = 3,
}

export declare const ContractErrors: {
    701: {message: "NotAuthorized"};
    702: {message: "InsufficientBalance"};
    703: {message: "OrderNotFound"};
    704: {message: "Overflow"};
    705: {message: "InvalidMatch"};
    706: {message: "InvalidPrice"};
}

export interface ClientInitializationParams {
    /** Public key of the account that will interact with the contract */
    publicKey: string;
    /** Callback for signing transactions generated by the client */
    signTransaction: SignTransactionCallback;
    /** URL of the RPC server */
    rpcUrl: string;
    /** Stellar contract ID */
    contractId: string;
    /** Network passphrase (Pubnet passphrase by default) */
    networkPassphrase?: string;
    /** Transaction fee (0.1 XLM by default) */
    fee?: string;
}

export type SignTransactionCallback = (
    tx: string,
    context: {network: string; networkPassphrase: string; accountToSign: string}
) => Promise<{signedTxXdr: string; signerAddress?: string}>;

export interface TradeArguments {
    /** Trading order behavior */
    kind: OrderKind,
    /** Trader address */
    trader: string;
    /** Tokens amount */
    amount: i128;
    /** Selling token address */
    selling: string;
    /** Buying token address */
    buying: string;
    /** Price a trader willing to accept */
    price: i128;
    /** List of order IDs to match before creating the order on-chain */
    orders: Array<u64>;
}

export interface SellTradeArguments extends TradeArguments {
    /** Amount of `selling` tokens to sell */
    amount: i128;
    /** Price a trader willing to accept, minimum `buying` tokens per 1 `selling` */
    price: i128;
}

export interface BuyTradeArguments extends TradeArguments {
    /** Amount of `buying` tokens to acquire */
    amount: i128;
    /** Price a trader willing to accept, maximum `selling` tokens per 1 `buying` */
    price: i128;
}

export declare class AxisContractClient {
    constructor(params: ClientInitializationParams);

    /**
     * Retrieve last order id
     * @returns Last created order id
     */
    last(): Promise<u64>;

    /**
     * Fetch existing order
     * @param id - ID of the order to fetch
     * @returns Order fetched from the storage
     */
    order(id: u64): Promise<Order>;

    /**
     * Cancel existing order
     * @param ids - ID of the order to cancel
     * @param trader - Trader address
     */
    cancel(ids: Array<u64>, trader: string): Promise<void>;

    /**
     * Fill existing orders using another matching order from the orderbook
     * @param trader - Trader address
     * @param takerOrderId - ID of the order that serves as a taker
     * @param orders - List of order IDs to match
     * @returns Amount of sold and bought tokens
     */
    fill_order(trader: string, takerOrderId: u64, orders: Array<u64>): Promise<[i128, i128]>;

    /**
     * Trade with DEX and create buy limit order if quote not executed in full
     * @param params - Trade parameters
     * @returns Amount of sold tokens, bought tokens, and ID of the newly created order if any
     */
    buy(params: BuyTradeArguments): Promise<[i128, i128, u64]>;

    /**
     * Trade with DEX and create sell limit order if quote not executed in full
     * @param params - Trade parameters
     * @returns Amount of sold tokens, bought tokens, and ID of the newly created order if any
     */
    sell(params: SellTradeArguments): Promise<[i128, i128, u64]>;
}
