import {Networks} from '@stellar/stellar-sdk'
import ContractClient from './contract-client.js'
import {ContractErrors, processSimulationErrors} from './errors.js'

export {ContractErrors}

/**
 * Smart contract client for trading with AXIS DEX
 */
export class AxisContractClient {
    /**
     * @param {ClientInitializationParams} params
     */
    constructor(params) {
        const options = {
            publicKey: params.publicKey,
            signTransaction: params.signTransaction,
            rpcUrl: params.rpcUrl,
            allowHttp: true,
            networkPassphrase: params.networkPassphrase || Networks.PUBLIC,
            contractId: params.contractId
        }
        this.client = new ContractClient(options)
        this.fee = params.fee || '100000'
    }

    /**
     * Trade with orders
     * @param {TradeArguments} params - Fill orders parameters
     * @return {Promise<[i128, i128]>} - Amount of sold and bought tokens
     * @throws {Error} - If any of the orders provided do not match selling/buying asset
     * @throws {Error} - If the trade causes an overflow
     */
    async fill(params) {
        const payload = {
            trader: params.trader,
            amount: params.amount,
            selling: params.selling,
            buying: params.buying,
            max_price: params.price,
            orders: params.orders
        }
        const tx = await this.client.fill(payload, {fee: this.fee})
        processSimulationErrors(tx)
        const res = await tx.signAndSend()
        return [res.result.sold, res.result.bought]
    }

    /**
     * Retrieve last order id
     * @return {Promise<u64>} - Last created order id
     */
    async last() {
        const tx = await this.client.last()
        processSimulationErrors(tx)
        return tx.result
    }

    /**
     * @param {u64} id - ID of the order to fetch
     * @return {Promise<Order>} - Order fetched from the storage
     */
    async order(id) {
        const tx = await this.client.order({id})
        processSimulationErrors(tx)
        return tx.result
    }

    /**
     * Cancel existing order
     * @param {u64} id - ID of the order to cancel
     * @param {string} trader - Trader address
     * @return {Promise<void>}
     * @throws {Error} - If trader is not the owner of the order
     */
    async cancel(id, trader) {
        const tx = await this.client.cancel({id, trader}, {fee: this.fee})
        processSimulationErrors(tx)
        await tx.signAndSend()
    }

    /**
     * Fill existing orders using another matching order from the orderbook
     * @param {string} trader - Trader address
     * @param {u64} takerOrderId - ID of the order that serves as a taker
     * @param {u64[]} orders - List of order IDs to match before creating the order on chain
     * @return {Promise<[i128, i128]>} - Amount of sold and bought tokens
     * @throws {Error} - If the taker order was not found
     * @throws {Error} - If any of the orders provided do not match selling/buying asset
     * @throws {Error} - If the trade causes an overflow
     */
    async fill_order(trader, takerOrderId, orders) {
        const tx = await this.client.fill_order({trader, taker_order_id: takerOrderId, orders}, {fee: this.fee})
        processSimulationErrors(tx)
        const res = await tx.signAndSend()
        return [res.result.sold, res.result.bought]
    }

    /**
     * Trade with DEX and create sell limit order if quote not executed in full
     * @param {TradeArguments} params
     * @return {Promise<[i128, i128, u64]>} - Amount of sold and bought tokens, ID of the newly created order if any
     * @throws {Error} - If the trader has insufficient balance
     * @throws {Error} - If any of the orders provided do not match selling/buying asset
     * @throws {Error} - If the trade causes an overflow
     */
    async sell_limit(params) {
        const payload = {
            trader: params.trader,
            amount: params.amount,
            selling: params.selling,
            buying: params.buying,
            price: params.price,
            ttl: params.ttl,
            orders: params.orders
        }
        const tx = await this.client.fill_order(payload, {fee: this.fee})
        processSimulationErrors(tx)
        const {result} = await tx.signAndSend()
        return [result[0], result[1], result[2]]
    }
}

/**
 * @typedef {{}} ClientInitializationParams
 * @property {string} publicKey - Public key of the account that will interact with the contract
 * @property {SignTransactionCallback} signTransaction - Callback for signing transactions generated by the client
 * @property {string} rpcUrl - URL of the RPC server
 * @property {string} [networkPassphrase] - Network passphrase (Pubnet passphrase by default)
 * @property {string} [fee] - Transaction fee (0.1 XLM by default)
 */

/**
 * @callback SignTransactionCallback - Callback for signing transactions generated by the client
 * @param {string} tx - Transaction XDR to sign
 * @param {{network: string, networkPassphrase: string, accountToSign: string}} context - Signing context
 * @return {Promise<{signedTxXdr: string, [signerAddress]: string}>} - Signed transaction response
 */

/**
 * @typedef {{}} TradeArguments
 * @property {string} trader - Trader address
 * @property {i128} amount - Amount of tokens to sell
 * @property {string} selling - Selling token address
 * @property {string} buying - Buying token address
 * @property {i128} price - Price a trader willing to accept
 * @property {u64} ttl - Time to live for an order (expired orders will be automatically purged)
 * @property {Array<u64>} orders - List of order IDs to match before creating the order on-chain
 */

/**
 * @typedef {{}} MethodOptions
 * @property {string} [fee] - Transaction fee (0.1 XLM by default)
 */

/**
 * @typedef {{}} Order
 * @property {u64} id - Order ID
 * @property {string} owner - Owner of the order
 * @property {OrderType} kind - Order type
 * @property {string} selling - Selling token address
 * @property {string} buying - Buying token address
 * @property {i128} amount - Amount of tokens to sell
 * @property {i128} price - Price of the order
 * @property {i128} quote - Total amount of tokens to buy
 * @property {u64} expires - Expiration time of the order
 */

